CREATE TABLE ORG_INFO (   
ID INT NOT NULL IDENTITY(1,1),
ORG_NAME VARCHAR(100) NOT NULL, 
INN CHAR (12),
LEGAL_ADDRESS VARCHAR(200),
ACT_ADDRESS VARCHAR(200)
PRIMARY KEY (ID))
CREATE TABLE PERSON_INFO (
ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
SURNAME VARCHAR(20) NOT NULL, 
NAME_ VARCHAR (20),
MIDDLE_NAME VARCHAR(20),
BIRTH_DATE DATE,
PASP_SER CHAR(4),
PASP_NUMB CHAR(6))


INSERT INTO ORG_INFO (ORG_NAME,INN,LEGAL_ADDRESS,ACT_ADDRESS) VALUES
('ООО Рога и копыта', '1234567890','г.Москва','г.Санкт-Петербург')


INSERT INTO PERSON_INFO (SURNAME,NAME_,MIDDLE_NAME,BIRTH_DATE,PASP_SER,PASP_NUMB) VALUES 
('Иванов','Иван','Иванович','1990.09.09','0123','012345');
